config/routes.rb
ShoobPhoto::Application.routes.draw do

  match 'contact' => 'contact#message', :via => 'GET'
  match 'contact' => 'contact#send_message', :via => 'POST'
  get 'contact/job_application'
  match 'contact/job_application' => 'contact#send_job_application', :via => 'POST'

  match 'printing' => 'catalog#printing'
  match 'printing/:product' => 'catalog#printing_product', :via => 'GET'
  match 'printing/:product' => 'cart#add_product', :via => 'POST', :as => 'cart_add_product'

  match 'purchase_pictures' => 'catalog#schools'
  match 'purchase_pictures/:school' => 'catalog#package_types'
  match 'purchase_pictures/:school/:package_type' => 'catalog#packages'
  match 'purchase_pictures/:school/:package_type/:package' => 'catalog#package', :via => 'GET'
  match 'purchase_pictures/:school/:package_type/:package' => 'cart#add_package', :via => 'POST', :as => 'cart_add_package'
  
  match 'senior_portraits/purchase_portraits' => 'catalog#senior_warning'
  
  match 'cart' => 'cart#index'
  match 'cart/:id/destroy_package' => 'cart#destroy', :as => :cart_destroy
  get 'cart/checkout'
  match 'cart/checkout' => 'cart#purchase', :via => :post
  get 'cart/receipt'
  
  match 'file_uploads/:id/:style/:filename' => 'file_upload#show'
  
  match 'barcode/:number' => 'barcodes#show'
  
  match 'download/*file' => 'contact#file', :via => 'GET'
  match 'download/*file' => 'contact#file_download', :via => 'POST', :as => 'download'

  match 'proof/:code' => 'proofs#show'

  match 'admin' => 'admin#index'
  get 'admin/help'
  get 'admin/log'
  scope '/admin' do
    resources :nav_links
    resources :pages
    resources :options
    resources :option_types
    resources :packages
    resources :package_types
    resources :schools
    resources :school_types
    resources :products
    match 'proofs/generate_code' => 'proofs#generate_code'
    match 'proofs/:id/upload_photos' => 'proofs#upload_photos'
    resources :proofs
    resources :orders
      match 'orders/:id/resend_receipt' => 'orders#resend_receipt', :as => 'order_resend_receipt'
    resources :users
    match 'mailer' => 'mailer#index'
    match 'mailer/deliver' => 'mailer#deliver', :via => 'POST'
    
    match 'runners/import' => 'runners#import'
    resources :runners # MODESTO MARATHON
    resources :races # MODESTO MARATHON
  end

  resources :user_sessions

  match 'login' => 'user_sessions#new'

  match 'logout' => 'user_sessions#destroy'

  resource :user

  match '*page' => 'pages#show', :constraints => proc {|request| Page.paths.include? request.fullpath }

  root :to => 'pages#show', :page => 'home'
  
  match 'internal_error.html' => 'errors#five_hundred'
  match '*path' => 'errors#four_oh_four'

end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :results, :dependent => :destroy
  has_many :races, :through => :results
  
  accepts_nested_attributes_for :results, :reject_if => proc {|attrs| attrs['distance'].blank?}, :allow_destroy => true
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  filter_access_to :all
  
  # GET /runners
  # GET /runners.xml
  def index
    @runners = Runner.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @runners }
    end
  end

  # GET /runners/1
  # GET /runners/1.xml
  def show
    @runner = Runner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @runner }
    end
  end

  # GET /runners/new
  # GET /runners/new.xml
  def new
    @runner = Runner.new
    3.times do
      @runner.results.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @runner }
    end
  end

  # GET /runners/1/edit
  def edit
    @runner = Runner.find(params[:id])
    3.times do
      @runner.results.build
    end
  end

  # POST /runners
  # POST /runners.xml
  def create
    @runner = Runner.new(params[:runner])

    respond_to do |format|
      if @runner.save
        format.html { redirect_to(@runner, :notice => 'Runner was successfully created.') }
        format.xml  { render :xml => @runner, :status => :created, :location => @runner }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @runner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /runners/1
  # PUT /runners/1.xml
  def update
    @runner = Runner.find(params[:id])

    respond_to do |format|
      if @runner.update_attributes(params[:runner])
        format.html { redirect_to(@runner, :notice => 'Runner was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @runner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.xml
  def destroy
    @runner = Runner.find(params[:id])
    @runner.destroy

    respond_to do |format|
      format.html { redirect_to(runners_url) }
      format.xml  { head :ok }
    end
  end
  
  def import
    if request.xhr? && params[:runner_import][:data]
      params[:runner_import][:columns].reject!{|k, v| v.blank?}
      data = params[:runner_import][:data].split(/\n/).reject(&:blank?)
      race_id = params[:runner_import].delete(:race_id)
      default_distance = params[:runner_import].delete(:distance)
      default_shadowchase = params[:runner_import].delete(:shadowchase)
      if !params[:runner_import][:columns].blank? && !data.blank?
        output = {:updated => [], :resolve => [], :imported => []}.with_indifferent_access
        columns = {}.with_indifferent_access
        params[:runner_import][:columns].each_pair do |index, column|
          columns[column.to_sym] = index.to_i
        end
        rows = []
        data.each do |row|
          row = row.split(/\t/)
          entry = {}.with_indifferent_access
          columns.each do |column, index|
            entry[column] = row[index]
          end
          rows << entry
        end
        rows.each do |row|
          result = nil
          distance = row.delete(:distance) || default_distance
          shadowchase = row.delete(:shadowchase) || default_shadowchase
          if (results = Runner.where(row.slice(:first_name, :last_name, :phone, :email))).any?
            result = results.first
            result.update_attributes(row.merge(:shadowchase => shadowchase))
            output[:updated] << results.first
          elsif (results = Runner.where(row.slice(:first_name, :last_name))).any?
            output[:resolve] << {:old => results.first.attributes.with_indifferent_access.except(:created_at, :updated_at, :id), :new => row.merge(:distance => distance, :race_id => race_id, :shadowchase => shadowchase), :id => results.first.id}
          else
            result = Runner.create(row.merge(:shadowchase => shadowchase))
            output[:imported] << result
          end
          unless result.nil?
            if distance.blank?
              result.results.find_or_create_by_race_id(race_id)
            else
              result.results.find_or_create_by_race_id_and_distance(race_id, distance)
            end
          end
        end
        ActiveRecord::Base.include_root_in_json = false
        render :json => output
      else
        render :text => 'Column assignments or data field is blank.', :status => 400
      end
    elsif request.xhr? && params[:runner_import][:resolve]
      race_id = params[:runner_import][:resolve].delete(:race_id)
      distance = params[:runner_import][:resolve].delete(:distance)
      result = nil
      if params[:runner_import][:resolve].delete(:new)
        result = Runner.create(params[:runner_import][:resolve])
      elsif params[:runner_import][:resolve].delete(:overwrite)
        result = Runner.find(params[:id])
        result.update_attributes(params[:runner_import][:resolve])
      end
      if distance.blank?
        result.results.find_or_create_by_race_id(race_id)
      else
        result.results.find_or_create_by_race_id_and_distance(race_id, distance)
      end
      render :nothing => true
    end
  end

end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation" class="full">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="third_box">
    <div class="field third">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field third">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field third">
      <%= f.label :gender %>
      <%= f.select :gender, ['', 'Female', 'Male'] %>
    </div>
    <div class="third check_box">
      <%= f.label :birthday %>
      <%= f.date_select :birthday, :start_year => Time.now.year - 100, :end_year => Time.now.year %>
    </div>
  </div>
  <div class="third_box">
    <div class="field third">
      <%= f.label :shirt_size %>
      <%= f.text_field :shirt_size %>
    </div>
    <div class="field third">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field third">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  </div>
  <div class="third_box">
    <div class="field third">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="field third">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="field third">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>
    <div class="field third">
      <%= f.label :zip_code %>
      <%= f.text_field :zip_code %>
    </div>
  </div>
  <hr class="full" />
  <table class="full">
    <tr>
      <th>Race</th>
      <th>Distance</th>
      <th>Time</th>
      <th>Destroy?</th>
    </tr>
  <% f.fields_for :results do |r| %>
    <tr>
      <th><%= r.collection_select :race_id, Race.all, :id, :name %></th>
      <th><%= r.text_field :distance %></th>
      <th><%= r.time_select :time, :include_seconds => true, :default => {:hour => 0, :minute => 0, :second => 0} %></th>
      <th><%= r.check_box :_destroy %></th>
    </tr>
  <% end %>
  </table>
  <hr class="full" />
  <div class="actions half">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1 class="full"><%= breadcrumbs :admin, :runners, "Editing #{@runner.name}" %></h1>
<%= render 'form' %>

app/views/runners/import.html.erb
<% @javascripts << 'runners/import' %>

<h1 class="full"><%= breadcrumbs :admin, :runners, :import %></h1>
<%= form_for :runner_import, :html => { :id => 'runner_import' } do |f| %>
  <div id="step_one">
    <p class="field fourth">
      Copy and paste data from excel sheet, without headers, into the box to the right. Select the race you wish to import these runners into.
    </p>
    <div class="field half">
      <%= f.text_area :data %>
    </div>
    <div class="fourth_box">
      <div class="fourth field">
        <%= f.label :race_id %>
        <%= f.collection_select :race_id, Race.all, :id, :name, :include_blank => true %>
      </div>
      <div class="fourth field">
        <%= f.label :distance %>
        <%= f.text_field :distance %>
      </div>
      <div class="fourth check_box">
        <%= f.label :shadowchase, 'Are these runners Shadowchase members?' %>
        <%= f.check_box :shadowchase %>
      </div>
      <div class="field fourth">
        <%= f.submit 'Begin Import' %>
      </div>
    </div>
  </div>
  <div id="step_two">
    <div class="field half">
      Now select which columns you would like to import to. Leave blank to discard.
    </div>
    <div class="field half">
      <%= f.submit 'Upload Records' %>
    </div>
    <hr class="full">
    <table id="runner_import_display" class="full">
      <tr>
        <th><%= f.select :columns, (Runner.column_names - ['created_at', 'updated_at', 'id'] + ['distance']).map{|c| [c.titleize, c]}, :include_blank => true %></th>
      </tr>
    </table>
  </div>
  <div id="step_three">
    <div class="full">
      <hr />
      <h3>Resolve</h3>
      <div class="resolve"></div>
    </div>
    <div class="full">
      <hr />
      <h3>Imported</h3>
      <div class="imported"></div>
    </div>
    <div class="full">
      <hr />
      <h3>Updated</h3>
      <div class="updated"></div>
    </div>
    <hr class="full" />
  </div>
<% end %>

app/views/runners/index.html.erb
<h1 class="full"><%= breadcrumbs :admin, :runners %></h1>
<hr class="full" />
<p class="left banner">
  <%= link_to 'New Runner', new_runner_path, :class => 'half' %>
  <%= link_to 'Import Runners', runners_import_path, :class => 'half align_right' %>
</p>
<hr class="full" />
<table class="full">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip code</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Shirt size</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @runners.each do |runner| %>
  <tr>
    <td><%= runner.first_name %></td>
    <td><%= runner.last_name %></td>
    <td><%= runner.address %></td>
    <td><%= runner.city %></td>
    <td><%= runner.state %></td>
    <td><%= runner.zip_code %></td>
    <td><%= runner.phone %></td>
    <td><%= runner.email %></td>
    <td><%= runner.gender %></td>
    <td><%= runner.shirt_size %></td>
    <td><%= runner.birthday %></td>
    <td><%= link_to 'Show', runner %></td>
    <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
    <td><%= link_to 'Destroy', runner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<hr class="full" />
<%= link_to 'New Runner', new_runner_path, :class => 'half' %>
<%= link_to 'Import Runners', runners_import_path, :class => 'half align_right' %>

app/views/runners/new.html.erb
<h1 class="full"><%= breadcrumbs :admin, :runners, :new_runner %></h1>
<%= render 'form' %>

app/views/runners/show.html.erb
<h1 class="full"><%= breadcrumbs :admin, :runners, "#{@runner.name.titleize}" %></h1>
<hr class="full" />
<div class="third">
  <p>
    <b>First name:</b>
    <%= @runner.first_name %>
  </p>
  <p>
    <b>Last name:</b>
    <%= @runner.last_name %>
  </p>
  <p>
    <b>Gender:</b>
    <%= @runner.gender %>
  </p>
  <p>
    <b>Birthday:</b>
    <%= @runner.birthday %>
  </p>
</div>
<div class="third">
  <p>
    <b>Shirt size:</b>
    <%= @runner.shirt_size %>
  </p>
  <p>
    <b>Email:</b>
    <%= @runner.email %>
  </p>
  <p>
    <b>Phone:</b>
    <%= @runner.phone %>
  </p>
</div>
<div class="third">
  <p>
    <b>Address:</b>
    <%= @runner.address %>
  </p>
  <p>
    <b>City:</b>
    <%= @runner.city %>
  </p>
  <p>
    <b>State:</b>
    <%= @runner.state %>
  </p>
  <p>
    <b>Zip code:</b>
    <%= @runner.zip_code %>
  </p>
</div>
<hr class="full" />
<table class="full">
  <tr>
    <th>Race</th>
    <th>Distance</th>
    <th>Time</th>
  </tr>
<% @runner.results.each do |result| %>
  <tr>
    <td><%= result.race.name %></td>
    <td><%= result.distance %></td>
    <td><%= result.time.try(:strftime, '%H:%M:%S') %></td>
  </tr>
<% end %>
</table>
<hr class="full" />
<%= link_to 'Edit', edit_runner_path(@runner), :class => 'full' %>