config/routes.rb
ShoobPhoto::Application.routes.draw do

  match 'contact' => 'contact#message', :via => 'GET'
  match 'contact' => 'contact#send_message', :via => 'POST'
  get 'contact/job_application'
  match 'contact/job_application' => 'contact#send_job_application', :via => 'POST'

  match 'printing' => 'catalog#printing'
  match 'printing/:product' => 'catalog#printing_product', :via => 'GET'
  match 'printing/:product' => 'cart#add_product', :via => 'POST', :as => 'cart_add_product'

  match 'purchase_pictures' => 'catalog#schools'
  match 'purchase_pictures/:school' => 'catalog#package_types'
  match 'purchase_pictures/:school/:package_type' => 'catalog#packages'
  match 'purchase_pictures/:school/:package_type/:package' => 'catalog#package', :via => 'GET'
  match 'purchase_pictures/:school/:package_type/:package' => 'cart#add_package', :via => 'POST', :as => 'cart_add_package'
  
  match 'senior_portraits/purchase_portraits' => 'catalog#senior_warning'
  
  match 'cart' => 'cart#index'
  match 'cart/:id/destroy_package' => 'cart#destroy', :as => :cart_destroy
  get 'cart/checkout'
  match 'cart/checkout' => 'cart#purchase', :via => :post
  get 'cart/receipt'
  
  match 'file_uploads/:id/:style/:filename' => 'file_upload#show'
  
  match 'barcode/:number' => 'barcodes#show'
  
  match 'download/*file' => 'contact#file', :via => 'GET'
  match 'download/*file' => 'contact#file_download', :via => 'POST', :as => 'download'

  match 'proof/:code' => 'proofs#show'

  match 'admin' => 'admin#index'
  get 'admin/help'
  get 'admin/log'
  scope '/admin' do
    resources :nav_links
    resources :pages
    resources :options
    resources :option_types
    resources :packages
    resources :package_types
    resources :schools
    resources :school_types
    resources :products
    match 'proofs/generate_code' => 'proofs#generate_code'
    match 'proofs/:id/upload_photos' => 'proofs#upload_photos'
    resources :proofs
    resources :orders
      match 'orders/:id/resend_receipt' => 'orders#resend_receipt', :as => 'order_resend_receipt'
    resources :users
    match 'mailer' => 'mailer#index'
    match 'mailer/deliver' => 'mailer#deliver', :via => 'POST'
    
    match 'runners/import' => 'runners#import'
    resources :runners # MODESTO MARATHON
    resources :races # MODESTO MARATHON
  end

  resources :user_sessions

  match 'login' => 'user_sessions#new'

  match 'logout' => 'user_sessions#destroy'

  resource :user

  match '*page' => 'pages#show', :constraints => proc {|request| Page.paths.include? request.fullpath }

  root :to => 'pages#show', :page => 'home'
  
  match 'internal_error.html' => 'errors#five_hundred'
  match '*path' => 'errors#four_oh_four'

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  
  def schools
    unless params[:search].blank?
      @results = School.where('title LIKE ?', "%#{params[:search]}%")
    end
    @school_types = SchoolType.all
  end

  def package_types
    @school = School.find_by_slug params[:school]
    @package_types = @school.package_types
  end

  def packages
    @school = School.find_by_slug params[:school]
    @package_type = @school.package_types.find_by_slug params[:package_type]
    @packages = @package_type.packages.order(:title)
  rescue
    raise ActiveRecord::RecordNotFound
  end

  def package
    @cart_package = CartPackage.new(
      :school => @school = School.find_by_slug(params[:school]),
      :package => @school.package_types.find_by_slug(params[:package_type]).packages.find_by_slug(params[:package])
    )
  end
  
  def senior_warning
  end
  
  def printing
    @products = Product.all
  end
  
  def printing_product
    @cart_product = CartProduct.new(
      :product => Product.find_by_slug(params[:product])
    )
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/package.html.erb
<% @javascripts << 'catalog/package' %>

<h1 class="two_thirds"><%= link_to @cart_package.school.title, "#{purchase_pictures_path}/#{@cart_package.school.slug}" %><span class="right_arrow"></span><%= link_to @cart_package.package.package_type.title, "#{purchase_pictures_path}/#{@cart_package.school.slug}/#{@cart_package.package.package_type.slug}" %><span class="right_arrow"></span><%= @cart_package.package.title %></h1>
<h1 class="third align_right"><%= link_to 'Cart', cart_path %></h1>
<div class="full">
  <%= image_tag @cart_package.package.image.url, :class => 'banner' if @cart_package.package.image? %>
  <% if @cart_package.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cart_package.errors.count, "error") %> prohibited this package from being ordered:</h2>
        <ul>
        <% @cart_package.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
</div>
<%= form_for @cart_package, :url => cart_add_package_path do |f| %>
  <%= f.hidden_field :school_id %>
  <%= f.hidden_field :package_id %>
  <div class="half_box">
    <div class="field fourth">
      <%= f.label :student_first_name, 'Student\'s First Name' %>
      <%= f.text_field :student_first_name %>
    </div>
    <div class="field fourth">
      <%= f.label :student_last_name, 'Student\'s Last Name' %>
      <%= f.text_field :student_last_name %>
    </div>
    <div class="field fourth">
      <%= f.label :student_grade, 'Student\'s Grade' %>
      <%= f.select :student_grade, (1..12).map{|number| [number.ordinalize]} + ['Kindergarten', 'Preschool', 'Headstart', 'Other'] %>
    </div>
    <% if @cart_package.school.teacher %>
      <div class="field fourth">
        <%= f.label :student_teacher, 'Student\'s Teacher' %>
        <%= f.text_field :student_teacher %>
      </div>
    <% end %>
    <% if @cart_package.package.package_type.sport_level %>
      <div class="field fourth">
        <%= f.label :student_sport_level, 'Student\'s Sport Level' %>
        <%= f.select :student_sport_level, [['Varsity'],['Junior Varsity'],['Freshman'],['N/A']] %>
      </div>
      <div class="field fourth">
        <%= f.label :student_sport, 'Student\'s Sport' %>
        <%= f.text_field :student_sport %>
      </div>
    <% end %>
    <% if @cart_package.package.purchase_id %>
      <div class="field fourth">
        <%= f.label :purchase_id, 'Purchase ID' %>
        <%= f.text_field :purchase_id %>
      </div>
    <% end %>
    <% if @cart_package.package.email_picture %>
      <div class="check_box fourth">
        <%= f.label :email_picture, 'Send a digital copy of the portrait to your email.' %>
        <%= f.check_box :email_picture %>
      </div>
    <% end %>
  </div>
  <% unless @cart_package.package.option_types(@cart_package.school).nil? %>
  <div id="options" class="half_box">
    <% @cart_package.package.option_types(@cart_package.school).each do |option_type| %>
      <div class="left">
        <h4 class="margins"><%= option_type.title %></h4>
      <% if option_type.multiple || option_type.options.count == 1 %>
        <% option_type.options.each do |option| %>
          <div class="check_box sixth">
            <label for="<%= "cart_package_option_ids_#{option_type.id}" %>">
              <%= image_tag option.image.url(:thumb), :class => 'twelfth' if option.image? %>
              <%= option.title %><%= number_to_currency(option.price(@cart_package.school), :show_zero => false, :format => ' - <span>%u%n</span>') %>
            </label>
            <%= check_box_tag "cart_package[option_ids][#{option_type.id}]", option.id %>
          </div>
        <% end %>
      <% else %>
        <% option_type.options.each do |option| %>
          <div class="check_box sixth">
            <label for="<%= "cart_package_option_ids_#{option_type.id}_#{option.id}" %>">
              <%= image_tag option.image.url(:thumb), :class => 'twelfth' if option.image? %>
              <%= option.title %><%= number_to_currency(option.price(@cart_package.school), :show_zero => false, :format => ' - <span>%u%n</span>') %>
            </label>
            <%= radio_button_tag "cart_package[option_ids][#{option_type.id}]", option.id %>
          </div>
        <% end %>
        <% unless option_type.required %>
          <div class="check_box sixth">
            <label for="<%= "cart_package_option_ids_#{option_type.id}_" %>">None</label>
            <%= radio_button_tag "cart_package[option_ids][#{option_type.id}]", nil %>
          </div>
        <% end %>
      <% end %>
      </div>
    <% end %>
  </div>
  <% end %>
  <hr class="full" />
  <div class="two_thirds align_right">
    Purchase <%= f.select :quantity, (1..30) %> at
    <b class="price"><%= number_to_currency @cart_package.package.price @cart_package.school %></b> each
  </div>
  <h3 class="sixth align_right">Total: <span class="total"><%= number_to_currency @cart_package.package.price @cart_package.school %></span></h3>
  <%= f.submit 'Add To Cart', :class => 'sixth' %>
<% end %>

app/views/catalog/package_types.html.erb
<h1 class="two_thirds"><%= @school.title %></h1>
<h1 class="third align_right"><%= link_to 'Cart', cart_path %></h1>
<hr class="full" />
<% @package_types.each do |type| %>
  <div class="fourth">
    <% link = "#{purchase_pictures_path}/#{@school.slug}/#{type.slug}" %>
    <% link = "/senior_portraits/purchase_portraits?back=#{purchase_pictures_path}/#{@school.slug}&continue=" + link if type.slug == 'senior_portraits' %>
    <%= link_to link do %>
      <%= image_tag type.image.url if type.image? %>
      <h2><%= type.title %></h2>
    <% end %>
  </div>
<% end %>
<hr class="full" />

app/views/catalog/packages.html.erb
<h1 class="two_thirds"><%= link_to @school.title, "#{purchase_pictures_path}/#{@school.slug}" %><span class="right_arrow"></span><%= @package_type.title %></h1>
<h1 class="third align_right"><%= link_to 'Cart', cart_path %></h1>
<div class="full">
  <% @packages.each do |package| %>
    <%= link_to "#{purchase_pictures_path}/#{@school.slug}/#{@package_type.slug}/#{package.slug}" do %>
      <%= image_tag package.image.url if package.image? %>
      <h2><%= "#{package.title} - #{number_to_currency package.price @school}" %></h2>
    <% end %>
    <hr />
  <% end %>
</div>

app/views/catalog/printing.html.erb
<h1 class="half">Printing Products</h1>
<h1 class="half align_right"><%= link_to 'Cart', cart_path %></h1>
<img src="/images/banners/print/print.jpg" class="banner full" />
<% @products.in_groups_of(3, false).each do |row| %>
  <% row.each do |product| %>
    <div class="third">
      <%= link_to "#{printing_path}/#{product.slug}" do %>
        <%= image_tag product.image.url if product.image? %>
        <h2><%= "#{product.title} - #{number_to_currency product.price} each" %></h2>
      <% end %>
    </div>
  <% end %>
  <hr class="full" />
<% end %>

app/views/catalog/printing_product.html.erb
<% @javascripts << 'catalog/printing_product' %>

<h1 class="half"><%= link_to 'Printing Products', printing_path %><span class="right_arrow"></span><%= @cart_product.product.title %></h1>
<h1 class="half align_right"><%= link_to 'Cart', cart_path %></h1>
<% if @cart_product.errors.any? %>
    <div id="error_explanation" class="full">
      <h2><%= pluralize(@cart_product.errors.count, "error") %> prohibited this product from being added to your cart:</h2>
      <ul>
      <% @cart_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @cart_product, :url => cart_add_product_path, :html => {:multipart => true} do |f| %>
  <%= f.hidden_field :product_id %>
  <div class="field third">
    <%= f.label :school %>
    <%= f.text_field :school %>
  </div>
  <div class="field two_thirds">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <hr class="full" />
  <div class="two_thirds align_right">
    Purchase <%= f.select :quantity, quantity_options(@cart_product.product.minimum_quantity) %> at
    <b class="price"><%= number_to_currency @cart_product.product.price %></b> each
  </div>
  <h3 class="sixth align_right">Total: <span class="total"><%= number_to_currency @cart_product.product.price %></span></h3>
  <%= f.submit 'Add To Cart', :class => 'sixth' %>
<% end %>

app/views/catalog/schools.html.erb
<h1 class="two_thirds">Purchase Pictures</h1>
<h1 class="third align_right"><%= link_to 'Cart', cart_path %></h1>
<%= image_tag '/images/banners/purchase_pictures/purchase_pictures.jpg', :class => 'full banner' %>
<%= form_tag purchase_pictures_path, :method => 'GET', :class => 'search' do %>
  <div class="field three_fourths">
    <%= text_field_tag :search, params[:search].blank? ? 'Enter school name to search' : params[:search], :rel => 'Enter school name to search' %>
  </div>
  <div class="field fourth">
    <%= submit_tag 'Search Schools', :name => nil %>
  </div>
<% end %>
<hr class="full" />
<% if @results %>
  <% if @results.any? %>
    <h2 class="full">Search Results</h2>
    <ul class="full list">
    <% @results.each do |school| %>
      <li><%= link_to school.title, "#{purchase_pictures_path}/#{school.slug}" %></li>
    <% end %>
    </ul>
  <% else %>
    <em class="full banner">No results were found for '<%= params[:search] %>'</em>
    <hr class="full" />
  <% end %>
<% end %>
<% @school_types.each do |type| %>
  <div class="third school_list">
    <h2><%= type.title %> Schools</h2>
    <ul class="list">
    <% type.schools.sort_by(&:title).group_by{|school| school.title[0].chr}.each do |letter, group| %>
      <li class="group_header"><%= letter %></li>
      <% group.each do |school| %>
        <li><%= link_to school.title, "#{purchase_pictures_path}/#{school.slug}" %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/catalog/senior_warning.html.erb
<h1 class="full">Purchasing Senior Portraits</h1>
<hr class="full" />
<div class="third">
  Before proceeding to our online store please note that the portraits
  you will be purchasing are those that were photographed at your school or at
  our studio on a yearbook only day.
</div>
<div class="third">
  This store is not for purchasing senior portraits that were taken at our Modesto location.
  If you would like to order pictures that were taken in the studio, please make an
  appointment by calling 1.888.257.4662 or 209.567.0748.
</div>
<%= link_to params[:continue] || purchase_pictures_path, :class => 'third' do %>
  <%= image_tag 'banners/senior_portraits/purchase_portraits/continue.jpg' %>
<% end %>
<%= link_to params[:back] || '/senior_portraits', :class => 'third' do %>
  <%= image_tag 'banners/senior_portraits/purchase_portraits/back.jpg' %>
<% end %>