config/routes.rb
ShoobPhoto::Application.routes.draw do

  match 'contact' => 'contact#message', :via => 'GET'
  match 'contact' => 'contact#send_message', :via => 'POST'
  get 'contact/job_application'
  match 'contact/job_application' => 'contact#send_job_application', :via => 'POST'

  match 'printing' => 'catalog#printing'
  match 'printing/:product' => 'catalog#printing_product', :via => 'GET'
  match 'printing/:product' => 'cart#add_product', :via => 'POST', :as => 'cart_add_product'

  match 'purchase_pictures' => 'catalog#schools'
  match 'purchase_pictures/:school' => 'catalog#package_types'
  match 'purchase_pictures/:school/:package_type' => 'catalog#packages'
  match 'purchase_pictures/:school/:package_type/:package' => 'catalog#package', :via => 'GET'
  match 'purchase_pictures/:school/:package_type/:package' => 'cart#add_package', :via => 'POST', :as => 'cart_add_package'
  
  match 'senior_portraits/purchase_portraits' => 'catalog#senior_warning'
  
  match 'cart' => 'cart#index'
  match 'cart/:id/destroy_package' => 'cart#destroy', :as => :cart_destroy
  get 'cart/checkout'
  match 'cart/checkout' => 'cart#purchase', :via => :post
  get 'cart/receipt'
  
  match 'file_uploads/:id/:style/:filename' => 'file_upload#show'
  
  match 'barcode/:number' => 'barcodes#show'
  
  match 'download/*file' => 'contact#file', :via => 'GET'
  match 'download/*file' => 'contact#file_download', :via => 'POST', :as => 'download'

  match 'proof/:code' => 'proofs#show'

  match 'admin' => 'admin#index'
  get 'admin/help'
  get 'admin/log'
  scope '/admin' do
    resources :nav_links
    resources :pages
    resources :options
    resources :option_types
    resources :packages
    resources :package_types
    resources :schools
    resources :school_types
    resources :products
    match 'proofs/generate_code' => 'proofs#generate_code'
    match 'proofs/:id/upload_photos' => 'proofs#upload_photos'
    resources :proofs
    resources :orders
      match 'orders/:id/resend_receipt' => 'orders#resend_receipt', :as => 'order_resend_receipt'
    resources :users
    match 'mailer' => 'mailer#index'
    match 'mailer/deliver' => 'mailer#deliver', :via => 'POST'
    
    match 'runners/import' => 'runners#import'
    resources :runners # MODESTO MARATHON
    resources :races # MODESTO MARATHON
  end

  resources :user_sessions

  match 'login' => 'user_sessions#new'

  match 'logout' => 'user_sessions#destroy'

  resource :user

  match '*page' => 'pages#show', :constraints => proc {|request| Page.paths.include? request.fullpath }

  root :to => 'pages#show', :page => 'home'
  
  match 'internal_error.html' => 'errors#five_hundred'
  match '*path' => 'errors#four_oh_four'

end

app/controllers/option_types_controller.rb
class OptionTypesController < ApplicationController
  filter_resource_access
  # GET /option_types
  # GET /option_types.xml
  def index
    @option_types = OptionType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @option_types }
    end
  end

  # GET /option_types/1
  # GET /option_types/1.xml
  def show
    @option_type = OptionType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @option_type }
    end
  end

  # GET /option_types/new
  # GET /option_types/new.xml
  def new
    @option_type = OptionType.new
    3.times{ @option_type.option_assignments.build }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @option_type }
    end
  end

  # GET /option_types/1/edit
  def edit
    @option_type = OptionType.find(params[:id])
    3.times{ @option_type.option_assignments.build }
  end

  # POST /option_types
  # POST /option_types.xml
  def create
    @option_type = OptionType.new(params[:option_type])

    respond_to do |format|
      if @option_type.save
        format.html { redirect_to(@option_type, :notice => 'Option type was successfully created.') }
        format.xml  { render :xml => @option_type, :status => :created, :location => @option_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @option_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /option_types/1
  # PUT /option_types/1.xml
  def update
    @option_type = OptionType.find(params[:id])

    respond_to do |format|
      if @option_type.update_attributes(params[:option_type])
        format.html { redirect_to(@option_type, :notice => 'Option type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @option_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /option_types/1
  # DELETE /option_types/1.xml
  def destroy
    @option_type = OptionType.find(params[:id])
    @option_type.destroy

    respond_to do |format|
      format.html { redirect_to(option_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/option_types_helper.rb
module OptionTypesHelper
end

app/views/option_types/_form.html.erb
<%= form_for(@option_type) do |f| %>
  <% if @option_type.errors.any? %>
    <div id="error_explanation" class="full">
      <h2><%= pluralize(@option_type.errors.count, "error") %> prohibited this option_type from being saved:</h2>

      <ul>
      <% @option_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="third_box">
    <div class="field third">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="check_box third">
      <%= f.label :required %>
      <%= f.check_box :required %>
    </div>
    <div class="check_box third">
      <%= f.label :multiple, 'Allow multiple selections' %>
      <%= f.check_box :multiple %>
    </div>
  </div>
  <div class="field third">
    <%= f.label :package_ids, 'Packages' %>
    <% Package.all.each do |package| %>
      <br />
      <%= link_to package do %>
        <% if package.package_type %>
          <%= package.package_type.slug %> <%= package.slug %>
        <% else %>
          (No Package Type) <%= package.slug %>
        <% end %>
      <% end %>
      <%= check_box_tag 'option_type[package_ids][]', package.id,
        @option_type.package_ids.include?(package.id), :class => 'right' %>
    <% end %>
    <%= hidden_field_tag 'option_type[package_ids][]', '' %>
  </div>
  <div class="field third">
    <%= f.label :option_ids, 'Options' %>
    <% Option.all.each do |option| %>
      <br />
      <%= link_to option do %>
        <% if option.option_type %>
          <%= option.option_type.title %> <%= option.title %>
        <% else %>
          (No Option Type) <%= option.title %>
        <% end %>
      <% end %>
      <%= check_box_tag 'option_type[option_ids][]', option.id,
        @option_type.option_ids.include?(option.id), :class => 'right' %>
    <% end %>
    <%= hidden_field_tag 'option_type[package_ids][]', '' %>
  </div>
  <hr class="full" />
  <table class="full nested_fields">
    <tr>
      <th>Package</th>
      <th>School</th>
      <th>Begin Date</th>
      <th>End Date</th>
      <th>Destroy?</th>
    </tr>
    <%= f.fields_for :option_assignments do |p| %>
    <tr>
      <td><%= p.select :package_id, Package.all.map{|package| ["#{package.package_type ? package.package_type.title : '(No package type)'} #{package.title}", package.id]}, :include_blank => true %></td>
      <td><%= p.grouped_collection_select :school_id, SchoolType.all, :schools, :title, :id, :title, :include_blank => true %></td>
      <td><%= p.date_select :begin, :include_blank => true %></td>
      <td><%= p.date_select :end, :include_blank => true %></td>
      <td><%= p.check_box :_destroy %></td>
    </tr>
    <% end %>
  </table>
  <hr class="full" />
  <div class="actions half">
    <%= f.submit %>
  </div>
<% end %>

app/views/option_types/edit.html.erb
<h1 class="full"><%= breadcrumbs :admin, :option_types, "Editing #{@option_type.title}" %></h1>
<%= render 'form' %>
<%= link_to 'Show', @option_type, :class => 'half align_right' %>

app/views/option_types/index.html.erb
<h1 class="full"><%= breadcrumbs :admin, :option_types %></h1>
<hr class="full" />
<table class="full">
  <tr>
    <th>Title</th>
    <th>Required</th>
    <th>Multiple Selections</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @option_types.each do |option_type| %>
  <tr>
    <td><%= option_type.title %></td>
    <td><%= option_type.required %></td>
    <td><%= option_type.multiple %></td>
    <td><%= link_to 'Show', option_type %></td>
    <td><%= link_to 'Edit', edit_option_type_path(option_type) %></td>
    <td><%= link_to 'Destroy', option_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<hr class="full" />
<%= link_to 'New Option type', new_option_type_path, :class => 'full' %>

app/views/option_types/new.html.erb
<h1 class="full"><%= breadcrumbs :admin, :option_types, :new_option_type %></h1>
<%= render 'form' %>
<%= link_to 'Back', option_types_path, :class => 'half align_right' %>

app/views/option_types/show.html.erb
<h1 class="full"><%= breadcrumbs :admin, :option_types, @option_type.title %></h1>
<hr class="full" />
<div class="third">
  <p>
    <b>Title:</b> <%= @option_type.title %>
  </p>
  <p>
    <b>Packages:</b>
    <% @option_type.packages.each do |package| %>
      <%= link_to package do %>
        <% if package.package_type %>
          <%= package.package_type.slug %> <%= package.slug %>
        <% else %>
          (No Package Type) <%= package.slug %>
        <% end %>
      <% end %>
    <% end %>
  </p>
</div>
<div class="third">
  <p>
    <b>Options:</b>
    <% @option_type.options.each do |option| %>
      <%= link_to option do %>
        <% if option.option_type %>
          <%= option.option_type.title %> <%= option.title %>
        <% else %>
          (No Option Type) <%= option.title %>
        <% end %>
      <% end %>
    <% end %>
  </p>
</div>
<div class="third">
  <p>
    <b>Required</b> <%= @option_type.required %>
  </p>
  <p>
    <b>Multiple selections</b> <%= @option_type.multiple %>
  </p>
</div>
<hr class="full" />
  <table class="full">
    <tr>
      <th>Package</th>
      <th>School</th>
      <th>Begin Date</th>
      <th>End Date</th>
      <th>Destroy?</th>
    </tr>
    <% @option_type.option_assignments do |price| %>
    <tr>
      <td><%= price.collection_select :package_id, Package.all, :id, :title, :include_blank => true %></td>
      <td><%= price.collection_select :school_id, School.all, :id, :title, :include_blank => true %></td>
      <td><%= price.date_select :begin, :include_blank => true %></td>
      <td><%= price.date_select :end, :include_blank => true %></td>
      <td><%= price.check_box :_destroy %></td>
    </tr>
    <% end %>
  </table>
<hr class="full" />
<%= link_to 'Edit', edit_option_type_path(@option_type), :class => 'full' %>